name: Get Unity Activation File

on:
  workflow_dispatch:

jobs:
  unity-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Usamos la versión v2 que es la oficial estable para este paso
      - name: Request activation file
        uses: game-ci/unity-request-activation-file@v2
        id: get-alf
        with:
          unityVersion: 6000.0.0f1

      # Guarda el archivo generado (.alf) en tus artefactos de GitHub
      - name: Upload ALF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity6-Activation-File
          path: ${{ steps.get-alf.outputs.filePath }}
