  unity-windows:
    needs: parity-core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Este paso mágico le va a pedir a Unity el archivo de activación (.alf)
      - name: Request activation file
        uses: game-ci/unity-request-activation-file@v4
        id: get-alf
        with:
          unityVersion: 6000.0.0f1 # O la versión de Unity 6 que uses

      # Este paso va a guardar el archivo para que lo puedas descargar de GitHub
      - name: Upload ALF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity6-Activation-File
          path: ${{ steps.get-alf.outputs.filePath }}
